-- Public schema tables
-- Main application tables

-- Template for creating tables with best practices:
-- create table if not exists public.table_name (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid references auth.users(id) on delete cascade,
--   name text not null,
--   description text,
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now()
-- );